layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
   sort_by options:
     - pushed
 #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: shubham.nagure
  hackerrank: nagure_shubham
  instagram: s_h_u_v_a_m_3
  # keybase: your_username
  linkedin: shubham-nagure
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 11828760
  # telegram: your_username
  twitter: shubham_nagure
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Amazon Web Services
    web_url: https://github.com/topics/aws
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Python
    web_url: https://github.com/topics/python

  - name: Automation
    web_url: https://github.com/topics/automation
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
